config/routes.rb
Rails.application.routes.draw do
  resources :jobs do
    resources :interviews
    patch '/update_status', to: 'jobs#update_status'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "jobs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :job
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :interviews

  STATUSES = ['Applied', 'Interviewing', 'Rejected', 'Accepted', 'Role Closed'].freeze
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: %i[show edit update destroy]
  before_action :get_job

  # GET /interviews or /interviews.json
  def index
    @interviews = Interview.all
  end

  # GET /interviews/1 or /interviews/1.json
  def show; end

  # GET /interviews/new
  def new
    @interview = @job.interviews.build
  end

  # GET /interviews/1/edit
  def edit; end

  # POST /interviews or /interviews.json
  def create
    @interview = @job.interviews.build(interview_params)

    respond_to do |format|
      if @interview.save
        format.html { redirect_to job_url(@job), notice: "Interview was successfully created." }
        format.json { render :show, status: :created, location: @interview }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1 or /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to job_path(@job), notice: "Interview was successfully updated." }
        format.json { render :show, status: :ok, location: @interview }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1 or /interviews/1.json
  def destroy
    @interview.destroy!

    respond_to do |format|
      format.html { redirect_to interviews_url, notice: "Interview was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_interview
    @interview = Interview.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def interview_params
    params.require(:interview).permit(:date, :start_time, :end_time, :questions_to_ask, :notes, :reflections, :job_id, :interviewer_name)
  end

  def get_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
    @applied = Job.where(status: 'Applied')
    @interviewing = Job.where(status: 'Interviewing')
    @rejected = Job.where(status: 'Rejected')
    @accepted = Job.where(status: 'Accepted')
    @closed = Job.where(status: 'Role Closed')
  end

  # GET /jobs/1 or /jobs/1.json
  def show; end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit; end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_status
    @job = Job.find_by(id: params[:job_id])
    respond_to do |format|
      format.js { render inline: "location.reload();" } if @job.update(status: params[:status])
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy!

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def job_params
    params.require(:job).permit(:company_name, :role_name, :referral, :status, :salary_min, :salary_max, :hourly_rate, :url, :hiring_manager_name, :hiring_manager_email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/interviews/_form.html.erb
<%= form_for([@job, @interview]) do |form| %>
  <% if interview.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
        <% interview.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label 'Date (MM/DD/YY)' %>
    <%= form.text_field :date %>   
  </div> 
  <div>
    <%= form.label :start_time %>
    <%= time_select("interview", "start_time", { minute_step: 15 }) %>
  </div> 
  <div>
  <%= form.label :end_time %>
  <%= time_select("interview", "end_time", { minute_step: 15 }) %>
</div> 
<div>
    <%= form.label 'Interviewer Name' %>
    <%= form.text_field :interviewer_name %>   
  </div> 
  <div>
    <%= form.label :questions_to_ask %>
    <%= form.text_area :questions_to_ask %>
  </div>
  <div>
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>
  <div>
    <%= form.label :reflections %>
    <%= form.text_area :reflections %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/interviews/_interview.html.erb
<div id="<%= dom_id interview %>">
    <p><span class='job_header'><%= interview.date.strftime("%B %e") %> at <%= interview.start_time.strftime("%l:%M%P") %>, with <%= interview.interviewer_name %> </span></p>
    <p><span class='job_header'>Questions to Ask: </span><%= interview.questions_to_ask %></p>
    <p><span class='job_header'>Notes: </span><%= interview.notes %></p>
    <p><span class='job_header'>Reflections: </span><%= interview.reflections %></p>
</div>
<div>
    <%= link_to "Edit this interview", edit_job_interview_path(@job, interview) %>
</div>

app/views/interviews/edit.html.erb
<h1>Editing interview</h1>

<%= render "form", interview: @interview %>

<br>

<div>
  <%= link_to "Show this interview", job_interview_path(@interview) %> |
  <%= link_to "Back to interviews", job_interviews_path(@interview.job) %>
</div>

app/views/interviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Interviews</h1>

<div id="interviews">
  <% @interviews.each do |interview| %>
    <%= render interview %>
    <p>
      <%= link_to "Show this interview", interview %>
    </p>
  <% end %>
</div>

<%= link_to "New interview", new_interview_path %>

app/views/interviews/new.html.erb
<h1>New interview</h1>

<%= render "form", interview: @interview %>

<br>

<div>
  <%= link_to "Back to interviews", job_interviews_path(@job) %>
</div>

app/views/interviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @interview %>

<div>
  <%= link_to "Edit this interview", edit_job_interview_path(@interview) %> |
  <%= link_to "Back to job", job_path(@interview.job_id) %>

  <%= button_to "Destroy this interview", @interview, method: :delete %>
</div>

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>   
  </div> 
  <div>
    <%= form.label :role_name %>
    <%= form.text_field :role_name %>
  </div>
  <div>
    <%= form.label :referral %>
    <%= form.text_field :referral %>
  </div>
  <div>
    <%= form.label :status %>
    <%= form.select :status, ['Applied', 'Interviewing', 'Rejected', 'Accepted', 'Role Closed'] %>
  </div>
  <div>
    <%= form.label :salary_min, 'Salary Minimum' %>
    <%= form.text_field :salary_min %>
  </div>
  <div>
    <%= form.label :salary_max, 'Salary Maximum' %>
    <%= form.text_field :salary_max %>
  </div>
  <div>
    <%= form.label :hourly_rate %>
    <%= form.text_field :hourly_rate %>
  </div>
  <div>
    <%= form.label :url, 'Job Posting URL' %>
    <%= form.text_field :url %>
  </div>
  <div>
    <%= form.label :hiring_manager_name %>
    <%= form.text_field :hiring_manager_name %>
  </div>
  <div>
    <%= form.label :hiring_manager_email %>
    <%= form.text_field :hiring_manager_email %>
  </div>

  <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div>
    <p><span class='job_header'>Company Name: </span><%= job.company_name %></p>
    <p><span class='job_header'>Role Name: </span><%= job.role_name %></p>
    <p><span class='job_header'>Status: </span> <%= job.status %></p>
    <p><span class='job_header'>Referral: </span><%= job.referral %></p>
    <p><span class='job_header'>Salary Minimum: </span><%= number_to_currency(job.salary_min) %></p>
    <p><span class='job_header'>Salary Maximum: </span><%= number_to_currency(job.salary_max) %></p>
    <p><span class='job_header'>Hourly Rate: </span><%= job.hourly_rate %></p>
    <p><span class='job_header'>Job Posting URL: </span><%= job.url %></p>
    <p><span class='job_header'>Hiring Manager Name: </span><%= job.hiring_manager_name %></p>
    <p><span class='job_header'>Hiring Manager Email: </span><%= job.hiring_manager_email %></p>
</div>

<div>
    <h2>Interviews</h2>
    <% job.interviews.order(date: 'desc').each do |interview| %>
        <%= render partial: 'interviews/interview', locals: { interview: interview } %>
    <% end %>    
</div>

app/views/jobs/_job_table.html.erb
<%= javascript_include_tag('packs/job_table') %>
<h3><%= status %></h1>

<table class='jobs_table'>
    <tr>
        <th>Company Name</th>
        <th>Role Name</th>
        <th>Status</th>
        <th>Referral</th>
        <th>Salary Range</th>
        <th>Hourly Rate</th>
        <th>Job Posting URL</th>
        <th>Hiring Manager Name</th>
        <th>Hiring Manager Email</th>
    </tr>
    <% jobs.each do |job| %>
        <tr>
            <td><%= link_to job.company_name, job_path(job) %></td>
            <td><%= job.role_name %></td>
            <td>
            <%= select_tag(
                'status',
                options_for_select(Job::STATUSES, selected: job.status),
                prompt: "Status",
                class: 'input-block-level chzn-select status-dropdown',
                id: 'status-dropdown',
                data: {
                    remote: true,
                    method: 'patch',
                    id: job.id
                }
            ) %>
            </td>
            <td><%= job.referral %></td>
            <td><%= "#{number_to_currency(job.salary_min)} - #{number_to_currency(job.salary_max)}" %></td>
            <td><%= number_to_currency(job.hourly_rate) %></td>
            <td><%= job.url %></td>
            <td><%= job.hiring_manager_name %></td>
            <td><%= job.hiring_manager_email %></td>
        </tr>
    <% end %>
</table>

<script type="text/javascript">
  function jobStatus(chk) {
    $.ajax({
      type: "PATCH",
      url: "/jobs/"+$(chk).attr('id')+"/update_status", 
      dataType: "script",
      data: { job: {status : chk.status} }
    });
  }
</script>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 id='job-tracker-title'>Job Tracker</h1>

<% Job::STATUSES.each do |status| %>
  <div>
      <%= render partial: 'jobs/job_table', locals: { jobs: Job.where(status: status), status: status } %>
  </div>
<% end %>

<%= button_to "New job", new_job_path, {method: :get, class: 'job-button'} %>
<%= javascript_include_tag "packs/job_table.js" %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %> |
  <%= link_to "Add interview", new_job_interview_path(@job) %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobInterviewTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src= 
"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"> 
    </script> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>